- name: Register auth
  ansible.builtin.uri:
    url: http://localhost/intelmq/v1/api/login
    body_format: form-urlencoded
    method: POST
    body:
      username: admin
      password: asdf
  register: auth
