- uri:
    url: http://localhost/intelmq/v1/api/queues
    return_content: yes
    headers:
      Authorization: '{{ auth.json.login_token }}'
  register: curlapiqueues
- name: Check queue status via API (for IntelMQ == 3.0)
  assert:
    that: "{{ lookup('file', 'assets/00_queues') | from_json }} == {{ curlapiqueues.content | from_json }}"
  when:
    intelmq_major_version == '3'
- name: Check queue status via API (for IntelMQ != 3.0)
  assert:
    that: "{{ lookup('file', 'assets/00_queues_pre30') | from_json }} == {{ curlapiqueues.content | from_json }}"
  when:
    intelmq_major_version != '3'
