- name: Start file-output bot
  command: nohup intelmqctl start file-output
  register: intelmqctlstartfileoutput
- name: Get status of file-output bot
  command: intelmqctl status file-output
  ignore_errors: yes
  register: intelmqctlstatusfileoutput
- assert:
    that: "'Bot file-output is running.' in intelmqctlstatusfileoutput.stdout"
- name: Stop file-output bot
  command: intelmqctl stop file-output
