- lineinfile:
    path: /assets/foo.txt
    create: true
    line: foobar
- name: Start file-output bot
  command: intelmqctl start file-output
- name: Start file-input bot
  command: intelmqctl start file-input
  ignore_errors: yes
- name: Stop file-output bot
  command: intelmqctl stop file-output
- slurp:
    src: /var/lib/intelmq/bots/file-output/events.txt
  register: events
- assert:
  # The output of the slurp command apparently gets parsed as a python dict, so we can't just
  # compare the string. Therefore there are multiple asserts:
    that:
      - "decoded_content['extra.file_name'] == 'foo.txt'"
      - "decoded_content['feed.accuracy'] == 100.0"
      - "decoded_content['feed.url'] == 'file://localhost/assets/foo.txt'"
      - "'time.observation' in decoded_content"
  vars:
    decoded_content: "{{ events['content'] | b64decode }}"
- name: Clean up
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /assets/foo.txt
    - /var/lib/intelmq/bots/file-output/events.txt
