- name: Run intelmqctl list configured bots
  command: intelmqctl --type json list bots --configured
  register: intelmqctllistbots
- name: Check output of intelmqctl list bots (--configured)
  assert:
    that: "{{ lookup('file', 'assets/list_bots_json') | from_json }} == {{ intelmqctllistbots.stdout | from_json }}"
