- name: Set user for IntelMQ API
  debconf:
    name: intelmq-api
    question: intelmq-api/user
    value: admin
    vtype: string
- name: Set password for IntelMQ API
  debconf:
    name: intelmq-api
    question: intelmq-api/password
    value: asdf
    vtype: password
- name: Set password-repeat for IntelMQ API
  debconf:
    name: intelmq-api
    question: intelmq-api/password-repeat
    value: asdf
    vtype: password
