- name: Add apt key
  apt_key:
    url: https://download.opensuse.org/repositories/home:sebix:intelmq/Debian_10/Release.key
    state: present
- name: Add apt key
  apt_key:
    url: https://download.opensuse.org/repositories/home:sebix:intelmq:/unstable/Debian_10/Release.key
    state: present
  when: lookup('env', 'intelmq_vagrant_test_stable') != 'yes'
- name: Setup IntelMQ stable Debian 10 repository
  apt_repository:
    repo: deb http://download.opensuse.org/repositories/home:/sebix:/intelmq/Debian_10/ /
    state: present
- name: Setup IntelMQ unstable Debian 10 repository
  apt_repository:
    repo: deb http://download.opensuse.org/repositories/home:/sebix:/intelmq:/unstable/Debian_10/ /
    state: present
  when: lookup('env', 'intelmq_vagrant_test_stable') != 'yes'
