# Are we running on a CI?
- name: Check if we are running on a CI
  set_fact:
    ci={{ lookup('env','CI') | default('false', true) }}
# Store the intelmq version in a variable
- name: Get intelmq version
  command: intelmqctl --version
  register: intelmqversion
- name: Set intelmq_version fact
  set_fact:
    intelmq_version={{ intelmqversion.stdout }}
- name: Set intelmq_major_version fact
  set_fact:
    intelmq_major_version={{ intelmqversion.stdout[:1] }}
- name: Print version
  debug:
    msg: IntelMQ Version {{ intelmq_version }} and IntelMQ Major Version {{ intelmq_major_version }}


# CLI related tests
#
# Those tests run intelmqctl
#
- name: Run CLI tests
  include_tasks: "{{ item }}"
  loop: "{{ query('fileglob', 'tasks/cli/*.yml') | sort }}"

# API related tests
#
# Those tests access the intelmq-api and manage the botnet
# Most of them depend on the 00_registerauth.yml task that provides the authentication token
#
- name: Run API tests
  include_tasks: "{{ item }}"
  loop: "{{ query('fileglob', 'tasks/api/*.yml') | sort }}"
  when: not ci | bool

# Manager related tests
#
# Those tests access the intelmq-manager webinterface
#
- name: Run Manager tests
  include_tasks: "{{ item }}"
  loop: "{{ query('fileglob', 'tasks/manager/*.yml') | sort }}"
  when: not ci | bool
