- name: Add apt key
  apt_key:
    url: "{{ repository_base }}/xUbuntu_20.04/Release.key"
    state: present
- name: Setup APT repository Ubuntu 20.04
  apt_repository:
    repo: "deb {{ repository_base }}/xUbuntu_20.04/ /"
    state: present
