- name: Add apt key
  apt_key:
    url: "{{ repository_base }}/xUbuntu_18.04/Release.key"
    state: present
- name: Setup APT repository Ubuntu 18.04
  apt_repository:
    repo: "deb {{ repository_base }}/xUbuntu_18.04/ /"
    state: present
