Vagrant.configure(2) do |config|

  config.vm.box = "generic/ubuntu2004"
  config.vm.network :forwarded_port, guest: 80, host: 8080

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "../../ansible/playbook.yml"
  end
end

